name: linux

# Only build PRs, the main branch, and releases.
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

# Use bash by default in all jobs
defaults:
  run:
    # Using "-l {0}" is necessary for conda environments to be activated
    # But this breaks on MacOS if using actions/setup-python:
    # https://github.com/actions/setup-python/issues/132
    shell: bash

jobs:
  test:

    name: ${{ matrix.case.os }} py${{ matrix.case.python-version }} ${{ matrix.case.name }}
    runs-on: ${{ matrix.case.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, ]
        case:
          - python-version: 3.8
            name: plain
            os: ubuntu
            conda: ""

    env:
      # Used to for coveralls flag
      OS: ${{ matrix.case.os }}
      PYTHON: ${{ matrix.case.python-version }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install numpy pytest pytest-flake8

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          python setup.py install
          pytest --flake8
